# Moira status codes and other constants, generated from Moira sources
#
# NOTE: this file was autogenerated from the following files:
#         mr_et.et 3956 2010-01-05 20:56:56Z zacheiss
#         moira.h 3956 2010-01-05 20:56:56Z zacheiss

# Error codes
MR_NOT_CONNECTED = 47836416
MR_CANT_CONNECT = 47836417
MR_VERSION_MISMATCH = 47836418
MR_ABORTED = 47836419
MR_UNKNOWN_PROC = 47836420
MR_DBMS_ERR = 47836421
MR_MORE_DATA = 47836422
MR_NO_MATCH = 47836423
MR_NO_HANDLE = 47836424
MR_ALREADY_CONNECTED = 47836425
MR_ARGS = 47836426
MR_NOT_UNIQUE = 47836427
MR_PERM = 47836428
MR_LIST = 47836429
MR_USER = 47836430
MR_STRING = 47836431
MR_TYPE = 47836432
MR_EXISTS = 47836433
MR_DATE = 47836434
MR_CLUSTER = 47836435
MR_MACHINE = 47836436
MR_SERVICE = 47836437
MR_FILESYS = 47836438
MR_PRINTER = 47836439
MR_QUEUE = 47836440
MR_DEVICE = 47836441
MR_ACE = 47836442
MR_NFSPHYS = 47836443
MR_FILESYS_EXISTS = 47836444
MR_QUERY_NOT_REENTRANT = 47836445
MR_RVD = 47836446
MR_NFS = 47836447
MR_FILESYS_ACCESS = 47836448
MR_USER_GROUP = 47836449
MR_ARG_TOO_LONG = 47836450
MR_NO_MEM = 47836451
MR_IN_USE = 47836452
MR_BAD_CLASS = 47836453
MR_INTERNAL = 47836454
MR_BAD_CHAR = 47836455
MR_BAD_GROUP = 47836456
MR_WILDCARD = 47836457
MR_NO_CHANGE = 47836458
MR_TAR_FAIL = 47836459
MR_OCONFIG = 47836460
MR_CCONFIG = 47836461
MR_FSTYPE = 47836462
MR_INTEGER = 47836463
MR_NO_ID = 47836464
MR_NO_FILESYS = 47836465
MR_NO_POBOX = 47836466
MR_NO_QUOTA = 47836467
MR_USER_AUTH = 47836468
MR_DEADLOCK = 47836469
MR_NOCRED = 47836470
MR_SETQUOTA = 47836471
MR_HESFILE = 47836472
MR_MISSINGFILE = 47836473
MR_MKCRED = 47836474
MR_NAMED = 47836475
MR_TARERR = 47836476
MR_PROTO = 47836477
MR_BUSY = 47836478
MR_DOWN = 47836479
MR_LISTLOOP = 47836480
MR_DBMS_SOFTFAIL = 47836481
MR_COREDUMP = 47836482
MR_SUBNET = 47836483
MR_ADDRESS = 47836484
MR_VERSION_LOW = 47836485
MR_VERSION_HIGH = 47836486
MR_RESERVED = 47836487
MR_QUALITY = 47836488
MR_CONTAINER = 47836489
MR_NEW_CONTAINER_NAME = 47836490
MR_ACCOUNT_NUMBER = 47836491
MR_CONTAINER_NO_PARENT = 47836492
MR_BAD_MAIL_STRING = 47836493
MR_NO_KRB4 = 47836494

# Error code descriptions
errors = {
    MR_NOT_CONNECTED : "Not connected to Moira server",
    MR_CANT_CONNECT : "Can't connect to Moira server",
    MR_VERSION_MISMATCH : "Moira version mismatch",
    MR_ABORTED : "Moira operation aborted",
    MR_UNKNOWN_PROC : "Unknown procedure",
    MR_DBMS_ERR : "DBMS system error occurred",
    MR_MORE_DATA : "More data is available from Moira",
    MR_NO_MATCH : "No records in database match query",
    MR_NO_HANDLE : "Unknown query handle",
    MR_ALREADY_CONNECTED : "Already connected to the moira server",
    MR_ARGS : "Incorrect number of arguments",
    MR_NOT_UNIQUE : "Arguments not unique",
    MR_PERM : "Insufficient permission to perform requested database access",
    MR_LIST : "No such list",
    MR_USER : "No such user",
    MR_STRING : "Unknown string",
    MR_TYPE : "Invalid type",
    MR_EXISTS : "Record already exists",
    MR_DATE : "Invalid date",
    MR_CLUSTER : "Unknown cluster",
    MR_MACHINE : "Unknown machine",
    MR_SERVICE : "Unknown service",
    MR_FILESYS : "Named file system does not exist",
    MR_PRINTER : "Unknown printer",
    MR_QUEUE : "Unknown queue",
    MR_DEVICE : "No such device",
    MR_ACE : "No such access control entity",
    MR_NFSPHYS : "Machine/device pair not in nfsphys",
    MR_FILESYS_EXISTS : "Named file system already exists",
    MR_QUERY_NOT_REENTRANT : "Cannot do query from callback routine",
    MR_RVD : "No such rvd",
    MR_NFS : "Specified directory not exported",
    MR_FILESYS_ACCESS : "Invalid filesys access",
    MR_USER_GROUP : "List is a user group",
    MR_ARG_TOO_LONG : "An argument is too long",
    MR_NO_MEM : "Server ran out of memory",
    MR_IN_USE : "Object is in use",
    MR_BAD_CLASS : "Specified class is not known",
    MR_INTERNAL : "Moira internal consistency failure",
    MR_BAD_CHAR : "Illegal character in argument",
    MR_BAD_GROUP : "Invalid group ID",
    MR_WILDCARD : "Wildcards not allowed in this case",
    MR_NO_CHANGE : "The database has not changed, files not rebuilt",
    MR_TAR_FAIL : "Unable to build archive of config files",
    MR_OCONFIG : "Unable to open DCM file",
    MR_CCONFIG : "Error closing DCM output file",
    MR_FSTYPE : "Unknown filesys type",
    MR_INTEGER : "String could not be parsed as an integer",
    MR_NO_ID : "Cannot allocate new ID",
    MR_NO_FILESYS : "Cannot find space for filesys",
    MR_NO_POBOX : "Cannot find space for pobox",
    MR_NO_QUOTA : "No default quota specified",
    MR_USER_AUTH : "Cannot find you in the database, access will be restricted",
    MR_DEADLOCK : "Database deadlock; try again later",
    MR_NOCRED : "Unable to install new credentials files",
    MR_SETQUOTA : "Failure setting user quota",
    MR_HESFILE : "Unable to copy hesiod file into nameserver directory",
    MR_MISSINGFILE : "Did not receive file for update",
    MR_MKCRED : "unable to compile database files",
    MR_NAMED : "name daemon failed to start",
    MR_TARERR : "Unable to extract DCM files",
    MR_PROTO : "Failed to put prototype files in new locker",
    MR_BUSY : "the database is busy; try again later",
    MR_DOWN : "the database is closed right now; try again later",
    MR_LISTLOOP : "Lists are not allowed to contain themselves as members",
    MR_DBMS_SOFTFAIL : "Temporary database failure, try again",
    MR_COREDUMP : "Subprocess coredumped",
    MR_SUBNET : "Bad subnet",
    MR_ADDRESS : "Bad address",
    MR_VERSION_LOW : "Client query version is older than server",
    MR_VERSION_HIGH : "Client query version is newer than server",
    MR_RESERVED : "That name is reserved",
    MR_QUALITY : "Password is too simple",
    MR_CONTAINER : "No such container",
    MR_NEW_CONTAINER_NAME : "The new container name is invalid",
    MR_ACCOUNT_NUMBER : "No such account number",
    MR_CONTAINER_NO_PARENT : "Parent container does not exist",
    MR_BAD_MAIL_STRING : "Address refers to nonexistent domain or MIT internal mail server",
    MR_NO_KRB4 : "Unable to complete operation using Kerberos v4",
}

# Definitions from moira.h
MR_SUCCESS = 0
MR_VERSION_1 = 1
MR_VERSION_2 = 2
MR_CONT = 0
MR_ABORT = -1
MR_NOOP = 0
MR_AUTH = 1
MR_SHUTDOWN = 2
MR_QUERY = 3
MR_ACCESS = 4
MR_DO_UPDATE = 5
MR_MOTD = 6
MR_PROXY = 7
MR_SETVERSION = 8
MR_KRB5_AUTH = 9
MR_MAX_PROC = 9
MR_FS_STUDENT = 0x0001
MR_FS_STAFF = 0x0004
MR_FS_MISC = 0x0008
MR_FS_GROUPQUOTA = 0x0010
UNIQUE_GID = "create unique GID"
UNIQUE_UID = "create unique UID"
UNIQUE_LOGIN = "create unique login ID"

